### ISSUE TITLE
Can't build a valid win32 application using node 5.12.0

### ISSUE THREAD

**Issue by pocesar** [kexplo/electron-edge#11]
I tried manually building the libraries using tools\build release 5.12.0, but it's trying to use iojs-1.2 libraries instead.

https://gist.github.com/pocesar/bb7f30047d38a3e42698a4afed52d5c9

Although it says successful, when I tried to test the build library it gives:

```
c:\nodejs\node_modules\electron-edge>test\test ia32 5.12.0

c:\nodejs\node_modules\electron-edge>rem usage: test.bat [ia32|x64 {version}], e.g. test.bat x64 0.10.0
Using node.js: c:\nodejs\node_modules\electron-edge\test\\..\lib\native\win32\ia32\5.12.0\node.exe
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\c:\nodejs\node_modules\electron-edge\build\Release\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\nodejs\node_modules\electron-edge\lib\edge.js:46:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\nodejs\node_modules\electron-edge\test\101_edge_func.js:1:74)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at C:\nodejs\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\nodejs\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\nodejs\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (C:\nodejs\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3


  CACHE https://api.nuget.org/v3/index.json
Restoring packages for c:\nodejs\node_modules\electron-edge\test\project.json
Writing lock file c:\nodejs\node_modules\electron-edge\test\project.lock.json
Restore complete, 344ms elapsed

NuGet Config files used:
    F:\ProgramData\NuGet\Config\Microsoft.VisualStudio.Offline.config
```

I'm using node 5.12.0, windows 10 x64, node-gyp 3.4.0, VS 2015, windows SDK 10. 
I can build anything natively using node-gyp (like socket.io, contextify, node-sass), so the tools might not be the culprit.

**Comment by OliverRadini** [comment]
Are you able to provide some detail on how you solved this?

**Comment by agracio** [comment]
If you are trying to build for a specific version of Electron take a look at this repo: https://github.com/agracio/electron-edge-js. It supports most Electron versions.
