### ISSUE TITLE
Could not find edge_nativeclr.node

### ISSUE THREAD

**Issue by JeremyBYU** [kexplo/electron-edge#12]
I'm using electron 1.2.0 with this package and am getting this error when launching the app.

```
App threw an error during load
Error: The specified module could not be found.
\\?\C:\Users\jeremy_castagnodev\Documents\development\tigerlily\tigerlily-salesman\build\node_modules\electron-edge\lib\
native\win32\x64\6.1.0\edge_nativeclr.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jeremy_castagnodev\Documents\development\tigerlily\tigerlily-salesman\build\node_mod
ules\electron-edge\lib\edge.js:46:8)

```

OS: Windows 7
Electron Version: 1.2.0
Electron-edge version: 5.0.3-pre1

**Comment by JeremyBYU** [comment]
I got it working.  I upgraded my node version to v6 and it seems to be working.  Only issue I have is with packaging the .dll in the .asar file.

Thanks!
