### ISSUE TITLE
The specified module could not be found edge_nativeclr.node

### ISSUE THREAD

**Issue by pmoleri** [kexplo/electron-edge#15]
Hi,
I'm getting this error when I try to install `electron-edge` `5.9.2-p0` on Windows 10. I was having the same error with `5.0.3-pre`.

```
>npm install electron-edge
`-- electron-edge@5.9.2-p0
  +-- edge-cs@1.0.0
  `-- nan@2.4.0

> electron-edge@5.9.2-p0 install C:\Work\test\node_modules\electron-edge
> node tools/install.js

log  : Restoring packages for C:\Work\test\node_modules\electron-edge\lib\bootstrap\project.json...
error: Package Edge.js 5.9.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Edge.js 5.9.2 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: Package Edge.js.CSharp 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Edge.js.CSharp 1.0.0 supports: netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
info : Committing restore...
log  : Writing lock file to disk. Path: C:\Work\test\node_modules\electron-edge\lib\bootstrap\project.lock.json
log  : C:\Work\test\node_modules\electron-edge\lib\bootstrap\project.json
log  : Restore failed in 760ms.

Errors in C:\Work\test\node_modules\electron-edge\lib\bootstrap\project.json
    Package Edge.js 5.9.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Edge.js 5.9.2 supports:
      - net40 (.NETFramework,Version=v4.0)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    Package Edge.js.CSharp 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Edge.js.CSharp 1.0.0 supports: netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

NuGet Config files used:
    C:\Users\pmoleri\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Project bootstrap (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling bootstrap for .NETCoreApp,Version=v1.0
C:\Work\test\node_modules\electron-edge\lib\bootstrap\project.json(13,27): error NU1002: The dependency Edge.js 5.9.2 does not support framework .NETCoreApp,Version=v1.0.
C:\Work\test\node_modules\electron-edge\lib\bootstrap\project.json(14,34): error NU1002: The dependency Edge.js.CSharp 1.0.0 does not support framework .NETCoreApp,Version=v1.0.

Compilation failed.
    0 Warning(s)
    2 Error(s)

Time elapsed 00:00:00.0125696

Load edge native library from: C:\Work\test\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr
***************************************
Error: The specified module could not be found.
\\?\C:\Work\test\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Work\test\node_modules\electron-edge\lib\edge.js:50:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
***************************************
Success: platform check for edge.js: node.js x64 v6.3.0
```

I have Visual Studio 2015 Update 3 and .Net Core installed, although from the README I understand that having .Net 4.5 is enough.

Node: v6.3.0

*\* Update **

When I try to use it:

```
C:\Work\test>node
> require("electron-edge")
Load edge native library from: C:\Work\test\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr
Error: The specified module could not be found.
\\?\C:\Work\test\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Work\test\node_modules\electron-edge\lib\edge.js:50:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
>
(To exit, press ^C again or type .exit)
>

C:\Work\test>dir C:\Work\test\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr.node
...
27/07/2016  16:06           157.696 edge_nativeclr.node
               1 File(s)        157.696 bytes
```

**Comment by pmoleri** [comment]
Ok, require directly from _node_ fails as it should because it isn't _electron_. The install message is a bit misleading but it doesn't do any harm.

This combination fixed the problem:
- node: v6.3.0
- electron: 1.3.0
- electron-edge: 5.9.2-p0
