### ISSUE TITLE
Uncaught Error: Specified procedure could not be found

### ISSUE THREAD

**Issue by Nostreim** [kexplo/electron-edge#16]
I am running into the following issue using electron-edge:

```
Uncaught Error: The specified procedure could not be found.
\\?\C:\dev\Projects\xxx\xxx\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr.node
Error: The specified procedure could not be found.
\\?\C:\dev\Projects\xxx\xxx\node_modules\electron-edge\lib\native\win32\x64\6.3.0\edge_nativeclr.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\Projects\xxx\xxx\node_modules\electron-edge\lib\edge.js:50:8)
```

I am referencing it in my electron application using the follow:

``` js
var edge = require('electron').remote.require('electron-edge');
```

I noticed while installing electron-edge via npm I had a similar warning referring to edge_nativeclr.node:

[node image](http://i.imgur.com/yq5HRQW.png)

I am running node v6.3.1 and electron v1.3.3

Any clues as to what might be happening?

**Comment by Nostreim** [comment]
I feel a bit silly but I was using an older version of electron globally (1.2.4). I updated my global instance of electron to the latest and was able to get the require statement to work.

**Comment by dougludlow** [comment]
I'm running into this same error, but after I've packaged the app. I check the path it's refering to for `edge_nativeclr.node` and sure enough it's there...

**Comment by dougludlow** [comment]
Ended up, I was missing a `.dll` edge needed: http://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found/
