### ISSUE TITLE
problem with electron 1.3.3 release

### ISSUE THREAD

**Issue by mksuper1** [kexplo/electron-edge#17]
Hi, the edge is not working with electron 1.3.3 release. 1.3.2 is ok. pls check. 

Error: The specified procedure could not be found.
\?\node_modules\electron-edge\lib\native\win32\ia32\6.1.0\edge_nativeclr.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen](ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node](ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\electron-edge\lib\edge.js:46:8)
Thanks

**Comment by kexplo** [comment]
Please Check your `electron-edge` version in `package.json`. it seemed to be old.

**Comment by mksuper1** [comment]
Hi,

thanks. It seems that if I use >npm i -save-dev electron-edge, it will install the old version.
I need to use >npm i -save-dev electron-edge@5.9.2-p0 so that it will pull down the new version.

thanks
