### ISSUE TITLE
Error: Module version mismatch

### ISSUE THREAD

**Issue by felisio** [kexplo/electron-edge#18]
Hi, Is not working with insert in electron main.js. pls check. I am using the current versions of this libraries
main.js:

``` javascript
const electron = require('electron')
const edge = require('electron-edge')
```

shell:

``` shell
App threw an error during load
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fabionunes/Developer/playground/electron-finger/node_modules/electron-edge/lib/edge.js:50:8)
```

**Comment by brunoalvesdefaria** [comment]
Same issue here:

```
A JavaScript error occurred in the main process
Error: Module version mismatch. Expected 50, got 49.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\git\NucleusDiagnosticWorkstation\electron\build\NDW-win32-x64\resources\app\node_modules\electron-edge\lib\edge.js:50:8)
```

**Comment by kjpou1** [comment]
Try running a rebuild over the native modules after the install:

`npm rebuild --runtime=electron --target=1.4.0 --disturl=https://atom.io/download/atom-shell`

or specifically for electron edge modules

`npm rebuild --runtime=electron --target=1.4.0 --disturl=https://atom.io/download/atom-shell electron-edge`

The --target above is the version you are targeting in my case it is 1.4.0 because I am using that version.

Also; [electron-rebuild](https://github.com/electron/electron-rebuild) can be used.
