### ISSUE TITLE
Can't load DLL

### ISSUE THREAD

**Issue by laduran** [kexplo/electron-edge#20]
I am unable to load the library here:
electron-edge\lib\native\win32\ia32\6.3.0\edge_nativeclr.node

It appears the library has been built with visual studio 2015 and now relies on msvcp140.dll. This file isn't distributed with the build that I have. I am running version 5.9.2-p0.

I worked around the problem by installing the CRT redist from VS 2015. Other people will certainly encounter this.

**Comment by kauevaz** [comment]
Hi!
I'm with the same problem in x64.
Installing node 6.5.0 and electron 1.4.0 don't resolve the issue.
the module work on the same machine, but if release and other pc with out crt( or linux/mac) dont work too with out mono installed(on released)).

**Comment by laduran** [comment]
@kauevaz You can work around the problem by installing the Visual C runtime on Windows. If you have visual studio installed you can just install the correct platform (x86/x64) from this path:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\1033

If you don't have it, I'm pretty sure you can find a redist installer for these with a quick Google search.

**Comment by kexplo** [comment]
You should be installed [VS 2015 redist](https://www.microsoft.com/en-US/download/details.aspx?id=48145).

I will update README.md

**Comment by kauevaz** [comment]
Hi, really thanks for the help!
I'm already have installed vs 2015 redist.

When I try to install electron-edge I have this output: 

```
\\?\C:\Projects\IntegratorTerminalElectron\node_modules\electron-edge\lib\native\win32\x64\6.5.0\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\IntegratorTerminalElectron\node_modules\electron-edge\lib\edge.js:49:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
***************************************
Success: platform check for edge.js: node.js x64 v6.5.0
```

But, It install fine, and in development or in release in same pc work really fine.
I remember that a few week's before when I installed electron-edge, its just downloaded/installed various dll's from vs, and now no...

If them, get the release and try to execute in another computer without VS 2015 redist, dont work, give error: electron-edge\lib\native\win32\ia32\6.3.0\edge_nativeclr.node not found.

Maybe I need to tell future users that VS 2015 redist is a pre-requisite?

But, after all... Its really the best module ever. Very thanks for all. Needing any help just call me.

**Comment by thomascayne** [comment]
For anyone who might experience similar issues on a release, distribution or production machine with `electron-edge\lib\native\win32\ia32\6.3.0\edge_nativeclr.node`:

Please make sure your clients download and install [VS 2015 redist](https://www.microsoft.com/en-US/download/details.aspx?id=48145)  as @kexplo mentioned above and [Microsoft .NET Framework 4+](https://www.microsoft.com/en-us/download/details.aspx?id=49981) **FULL** version. 

One of my clients machine had "Microsoft .NET Framework 4.6.2 _Preview_". For whatever reason that version doesn't work with `electron-edge` which caused a "not found" error.

Thank you for such a wonderful module.

**Comment by CodeLiftSleep** [comment]
I am getting the same error messag and already have both of those installed---I opened it in dependancy walker and I see a bunch of missing dependancies on API-MS-WIN and also Node.dll...I am at a loss as to how to resolve this...any help would be appreciated

![image](https://cloud.githubusercontent.com/assets/17439424/21472891/eca44d3a-cabb-11e6-849a-4611b2a09885.png)


![image](https://cloud.githubusercontent.com/assets/17439424/21472877/7e514a72-cabb-11e6-9fda-4a813949e850.png)

**Comment by kauevaz** [comment]
Hi!
I Solved the release problems copying these four dll's in APP folder( and after first start copying to root (with FS)
concrt140.dll,msvcp140.dll,vccorlib140.dll,vcruntime140.dll
I maked a x32 copy two( in another folder, and check before fs copy the versions
