### ISSUE TITLE
Build for electron 1.6.0

### ISSUE THREAD

**Issue by mkazlauskas** [kexplo/electron-edge#29]
Title says it all, would be really useful.

The release is currently at [beta](https://github.com/electron/electron/releases/tag/v1.6.0).

**Comment by davidcraddock** [comment]
yes please

**Comment by akerbergmika** [comment]
+1.

**Comment by kirilpopov** [comment]
+ 1

**Comment by dev0tion** [comment]
Yes please!

**Comment by thomascayne** [comment]
This would be great. I'm stuck using Electron 1.4.4 because Electron Edge (EE) is not upgraded. Without EE the entire program is pointless. Unless I find an alternative. Any ideas anyone?

**Comment by mkazlauskas** [comment]
I ended up using original `edge` (not `electron-edge`). I don't know how edge is built but it seems to be working fine using the same node version as documented by edge.

**Comment by pmoleri** [comment]
Hi @mkazlauskas,

I tried installing `electron@1.6.2` (node 7.4.0) and `edge@6.5.1`.
Build for node 7.4.0 `node_modules\edge\tools\build.bat release "7.4.0"`.
From inside electron `require("edge")` throw this error:
```
Uncaught Error: The specified procedure could not be found.
\\?\C:\...\node_modules\edge\build\Release\edge_nativeclr.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\...\node_modules\edge\lib\edge.js:57:8)
    at Object.<anonymous> (C:\...\node_modules\edge\lib\edge.js:177:3)
```

The file exists, so I guess the built file for `node 7.4.0` isn't compatible with `electron 1.6.2`.

Is it still working for you?

**Comment by kexplo** [comment]
It needs edge.js which supports node.js v7.0.
Please track edge's [issue](https://github.com/tjanczuk/edge/issues/507).

**Comment by pmoleri** [comment]
Hi @kexplo 
I successfully built `electron-edge` for `1.6.2` on Windows 10 and seems to be working fine.
1. edit `node_modules\electron-edge\tools\build.bat` update `--target=1.6.2`.
2. run build: `node_modules\electron-edge\tools\build.bat release "7.4.0"`

For anyone else wanting to build, it's important to [configure node-gyp correctly](https://github.com/nodejs/node-gyp).

**Comment by kexplo** [comment]
OMG!!
The problem is outdated node-gyp!
After upgrading node-gyp, the build succeeded!
Thank you @pmoleri

**Comment by kexplo** [comment]
I just released new version of electron-edge to [npm](https://www.npmjs.com/package/electron-edge)

**Comment by SeanSnyders** [comment]
@kexplo It seems that `electron-edge 6.5.5` is build for `NODE_MODULE_VERSION 51` where `electron 1.6.x` is running `NODE_MODULE_VERSION 53.` as per their [release notes](https://github.com/electron/electron/releases/tag/v1.6.0):
![image](https://cloud.githubusercontent.com/assets/1384135/24687594/9d9a4e22-1a0e-11e7-854d-d8b51bc6cd47.png)

I get this error when trying to launch my electron app on OSX:
```
App threw an error during load
Error: The module '<project_folder>/app/node_modules/electron-edge/build/Release/edge_nativeclr.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

Using `node 7.4.0`, `npm 4.0.5` as per electron's website:
![image](https://cloud.githubusercontent.com/assets/1384135/24687712/61f5f58c-1a0f-11e7-8572-1cdbb7c47a18.png)

Running `npm install` does indeed build electron-edge.

**Comment by pmoleri** [comment]
Hi, I guess this PR #21 is needed.

@SeanSnyders you probably can copy & paste the code in your `tools/install.js`

If that works, @kexplo should be able to _cherry-pick_ that commit into the 1.6.4 branch.

**Comment by kexplo** [comment]
I forgot.
I just *cherry-picked* that commit.

And I mistakenly created a branch named `electron_v1.6.4` with the wrong name, so I created a new branch named `electron_v1.6.2`.

Please make sure it works properly.
I can not use macOS now.

**Comment by me0262** [comment]
@SeanSnyders I'm getting this version conflict on Linux as well.
I've resolved by 'npm install electron-rebuild' and running 'node_modules/.bin/electron-rebuild'
This must be a problem on electron's side, because the latest Node is version 51 (unless they're supporting v8 LTS)

**Comment by Menendez-Oscar** [comment]
For those getting the mismatch error on Linux. You'll need to add a file .npmrc to the root directory of your project. 
```
runtime = electron
target = 1.6.2
target_arch = armv7l
disturl = https://atom.io/download/atom-shell
```
This example works for raspberry pi running Ubuntu mate. Replace the target_arch with whatever your system's architecture is.
