### ISSUE TITLE
i can't get it to install

### ISSUE THREAD

**Issue by scottbentley** [kexplo/electron-edge#34]
I can't find a reason or solution to this at all, but electron-edge won't install cleanly.

Ubuntu 16.04.2 "Xenial"
Node 6.10.2
Electron 1.6.2
.NET Core 1.0.1

As far as I can tell the .NET Core is installed and working correctly, as is node and electron.    The following is the install output.

===========================================================================
bentleys@BENTLEYS:~/Documents/ext_root/tagworkspace/defsapp/electron$ npm install electron-edge

&gt; edge-cs@1.2.1 install /home/bentleys/Documents/ext_root/tagworkspace/defsapp/electron/node_modules/edge-cs
&gt; node tools/install.js

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

&gt; electron-edge@6.5.5 install /home/bentleys/Documents/ext_root/tagworkspace/defsapp/electron/node_modules/electron-edge
&gt; node tools/install.js

make: Entering directory '/home/bentleys/Documents/ext_root/tagworkspace/defsapp/electron/node_modules/electron-edge/build'
  TOUCH Release/obj.target/edge_nativeclr.stamp
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal_utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/trace.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/fxr/fx_ver.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/fxr/fx_muxer.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json_parsing.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/json/json_serialization.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/json/casablanca/src/utilities/asyncrt_utils.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_format.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_entry.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/deps/deps_resolver.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/args.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/coreclr.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/libhost.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/host/runtime_config.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal.unix.o
  SOLINK_MODULE(target) Release/obj.target/edge_coreclr.node
  COPY Release/edge_coreclr.node
  ACTION binding_gyp_build_managed_target_restore_bootstrap_packages lib/bootstrap/project.lock.json
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
build_managed.target.mk:13: recipe for target 'lib/bootstrap/project.lock.json' failed
make: *** [lib/bootstrap/project.lock.json] Error 1
make: Leaving directory '/home/bentleys/Documents/ext_root/tagworkspace/defsapp/electron/node_modules/electron-edge/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-72-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/bentleys/Documents/ext_root/tagworkspace/defsapp/electron/node_modules/electron-edge
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
defsapp@1.0.0 /home/bentleys/Documents/ext_root/tagworkspace/defsapp/electron
└─┬ electron-edge@6.5.5 
  ├── edge-cs@1.2.1 
  └── nan@2.6.1 

npm WARN defsapp@1.0.0 No repository field.

===========================================================================

**Comment by scottbentley** [comment]
Turns out it was .NET Core 1.0.1.  With the new point update they changed the format of the proj file, it no longer accepts "project.proj".

I replaced 1.0.1 with 1.0.0-preview2 and all is well.
