### ISSUE TITLE
'npm install electron-edge' fails on CentOS and NetCore SDK 1.0.1

### ISSUE THREAD

**Issue by me0262** [kexplo/electron-edge#36]
Hi! I'm getting some problems when installing my dependencies when I bring over my application to linux. I'm also getting problems when running the application (module compiled against a different Node.js version using 48, requires 53), but I think this is the root cause.

This is installed on CentOS 7.3, using Node 6.10 from EPEL, and dotnet-dev-centos-x64.1.0.1.tar.gz from microsoft.
Mono is not installed, although it has the same results.

The following was performed when no node_modules folder is present.
dependencies in package.json:
"electron": "^1.4.x",
"electron-debug": "^1.1.0",
"electron-edge": "^6.5.4",
"node-gyp": "^3.5.0",

Sample output:
[devel@CentOS7 electron-linux]$ npm install electron-edge

> edge-cs@1.2.1 install /home/devel/Desktop/electron-linux/node_modules/edge-cs
> node tools/install.js

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

> electron-edge@6.5.5 install /home/devel/Desktop/electron-linux/node_modules/electron-edge
> node tools/install.js

> make: Entering directory `/home/devel/Desktop/electron-linux/node_modules/electron-edge/build'
> TOUCH Release/obj.target/edge_nativeclr.stamp
> CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o

*** SNIP - MORE COMPILING ***

> CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/pal/pal.unix.o
> SOLINK_MODULE(target) Release/obj.target/edge_coreclr.node
> COPY Release/edge_coreclr.node
> ACTION binding_gyp_build_managed_target_restore_bootstrap_packages lib/bootstrap/project.lock.json
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> make: *** [lib/bootstrap/project.lock.json] Error 1
> make: Leaving directory `/home/devel/Desktop/electron-linux/node_modules/electron-edge/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.16.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/devel/Desktop/electron-linux/node_modules/electron-edge
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
electron-linux-project /home/devel/Desktop/electron-linux
└─┬ electron-edge@6.5.5 
  ├── edge-cs@1.2.1 
  └── nan@2.6.2 

[devel@CentOS7 electron-linux]$

**Comment by me0262** [comment]
Solved.
Issue pertains to newer SDKs using an XML project format (*.csproj) over the old project.json. This apparently was a hard change and was not transitioned out of dotnet.
dotnet does, however, have a migration mechanism that you can run 'dotnet migrate' in the node_modules/electron-edge and node_modules/edge-cs folders and it will search and convert the project.json files to their .csproj equivalent.
This can be done after you're installed electron-edge and edge-cs, then 'npm rebuild electron-edge' and 'npm rebuild edge-cs'

**Comment by me0262** [comment]
close when confirmed. this is a change that should be made in the repo (along with the edge-cs repo).
