### ISSUE TITLE
Failed to find the Edge.js runtime assembly in the dependency manifest list

### ISSUE THREAD

**Issue by weliwita** [kexplo/electron-edge#39]
Hi,
I'm trying to get started with electron-edge. I could run the first hello world example using .net 4.5. But when I try to run the same example using core CLR I get following exception.

```
App threw an error during load
Error: Failed to find the Edge.js runtime assembly in the dependency manifest list.  Make sure that your project.json file has a reference to the Edge.js NuGet package.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Personal\TrainingCode\aspnetcore\newClean\node_modules\electron-edge\lib\edge.js:52:10)
    at Object.<anonymous> (D:\Personal\TrainingCode\aspnetcore\newClean\node_modules\electron-edge\lib\edge.js:174:3)
```

My setup is as follows.
Windows 10 64bit
1. npm install electron-edge
2. used dotnet migrate and npm rebuild to build electron-edge and edge-cs
3. ran sample for .net 4.5
```
var helloWorld = edge.func(function () {/*
    async (input) => {
        return ".NET Welcomes " + input.ToString();
    }
*/});

  helloWorld('JavaScript', function (error, result) {
      if (error) throw error;
      console.log(result);
  });

```
It prints the output and worked fine.

Then I switched to core CLR
`set EDGE_USE_CORECLR=1`

Ran the app and got the exception above. I wasted about a day to get this to work.

Does anyone have a clue?

**Comment by weliwita** [comment]
Could get away with setting the dotnet sdk version to older version by adding `global.json` file
```
{
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
```
I guess released dotnetcore sdks are not yet supported.
