### ISSUE TITLE
Fix: msbuild fails during install - unsupported project.json

### ISSUE THREAD

**Issue by CzBuCHi** [kexplo/electron-edge#41]
during install msbuild print 'no project found' warning and quits ... 
its during command node tools/install.js - because lib/bootstrap/project.json file is no longer supported ...

after creating  lib/bootstrap/project.csproj with content bellow and building it in VS2017 msbuild no longer prinnts 'no project found' ...

```xml
<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFramework>netcoreapp1.0</TargetFramework>
   </PropertyGroup>
   <ItemGroup>      
      <PackageReference Include="Edge.js" Version="7.10.1" />
      <PackageReference Include="Edge.js.CSharp" Version="1.2.0" />
   </ItemGroup>
</Project>
```

**Comment by weliwita** [comment]
@CzBuCHi I'm quite new to edge and dotnet core. But I faced the same with VS2015, You could have done the same with `dotnet migrate` and` npm rebuild` to build `electron-edge` and` edge-cs`. even thought this was building fine, I could not get this working against a released .net core version. Only I could point to an older version and get this running without migrating to csproj format. https://github.com/kexplo/electron-edge/issues/39

**Comment by JorgeHawkins** [comment]
I also have a similar issue:

```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
***************************************
Error: The edge module has not been pre-compiled for node.js version v8.2.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (C:\Root\App\app-contents\node_modules\electron-edge\lib\edge.js:18:11)
    at Object.<anonymous> (C:\Root\App\app-contents\node_modules\electron-edge\lib\edge.js:30:102)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Root\App\app-contents\node_modules\electron-edge\tools\checkplatform.js:2:2)
***************************************
Success: platform check for edge.js: node.js x64 v8.2.1
npm WARN Invalid name: "Aplicación Prototipo"
npm WARN app-contents No description
npm WARN app-contents No repository field.
npm WARN app-contents No README data
npm WARN app-contents No license field.

+ electron-edge@6.5.5
```

This error appear when trying to install through `npm`.

**Comment by JohnnyFun** [comment]
fwiw, I had this error after I had deleted my node_modules/bin (and any other bin folders recursively inside my node_modules folder). Simply deleting node_modules and running `npm install` got me back to happy land.

**Comment by agracio** [comment]
@JorgeHawkins please take a look at this issue: https://github.com/kexplo/electron-edge/issues/47.
@CzBuCHi this is an issue related to support for .NET Core above 1.0.0, take a look at this issue: https://github.com/kexplo/electron-edge/issues/48
