### ISSUE TITLE
Electron-Edge fails to install with a MSBuild error

### ISSUE THREAD

**Issue by JorgeHawkins** [kexplo/electron-edge#47]
When trying to install `electron-edge` through `npm`, the application does not install correctly, rendering the package useless:

```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
***************************************
Error: The edge module has not been pre-compiled for node.js version v8.2.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (C:\Root\App\app-contents\node_modules\electron-edge\lib\edge.js:18:11)
    at Object.<anonymous> (C:\Root\App\app-contents\node_modules\electron-edge\lib\edge.js:30:102)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Root\App\app-contents\node_modules\electron-edge\tools\checkplatform.js:2:2)
***************************************
Success: platform check for edge.js: node.js x64 v8.2.1
npm WARN Invalid name: "Aplicación Prototipo"
npm WARN app-contents No description
npm WARN app-contents No repository field.
npm WARN app-contents No README data
npm WARN app-contents No license field.

+ electron-edge@6.5.5
added 3 packages in 9.01s
```

Node.JS version: `8.2.1`
NPM version: `5.3.0`
Electron version: `1.6.11`

**Comment by tpetrina** [comment]
Same here

 - Node.JS version 8.4.0
 - NPM version 5.3.0
 - Electron version 1.6.10

**Comment by agracio** [comment]
You will see that error when installing `electron-edge` on any Node.js version except 7.x, but will function correctly as long as you use it with supported Electron version.
