### ISSUE TITLE
make error on Ubuntu 17.10

### ISSUE THREAD

**Issue by MatteoMeil** [kexplo/electron-edge#55]
I'm on ubuntu 17.10 with .NET core 2.13 and Mono 5.8. First time I tried to install electron-edge I got an error due to new version of dot net, so I ran `dotnet migrate` in electron-edge's directory and then `npm rebuild electron-edge` in main working directory. The result is this error:
```
make: Entering directory '/home/matteo/Scrivania/electron-quick-start/node_modules/electron-edge/build'
make: *** No rule to make target '../lib/bootstrap/project.json', needed by 'lib/bootstrap/project.lock.json'.  Stop.
make: Leaving directory '/home/matteo/Scrivania/electron-quick-start/node_modules/electron-edge/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/matteo/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/home/matteo/.nvm/versions/node/v6.9.0/bin/node" "/home/matteo/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/matteo/Scrivania/electron-quick-start/node_modules/electron-edge
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
How can I fix this?

**Comment by agracio** [comment]
Try https://github.com/agracio/electron-edge-js it has support for .NET Core 1.1 - 2.x. No need to rebuild.
You can also take a look at .NET Core quick-start here:  https://github.com/agracio/electron-edge-js-quick-start.
Edit: I have a suspicion that quick start might not work on Linux as it struggles to find external dlls. Let me know.

**Comment by MatteoMeil** [comment]
Solved removing .NET
